"""BizLens LangGraph Workflow — 4-Agent DAG

Nodes: planner → code_interpreter → visualization → insight

Day 3: code_interpreter → real LLM code gen + sandbox execution + 3-retry self-healing.
Day 4: visualization → real LLM chart type selection + Plotly code gen + sandbox execution.
Day 5: insight → real LLM report generation + MCP knowledge injection.
"""

import logging
from typing import Any, TypedDict

from langgraph.graph import END, StateGraph

from agents.planner import plan_analysis
from agents.code_interpreter import execute_analysis
from agents.visualization import generate_chart
from agents.insight import generate_insight_report

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# AnalysisState — shared state flowing through the DAG
# ---------------------------------------------------------------------------

class AnalysisState(TypedDict, total=False):
    """State that flows through all 4 Agent nodes.

    Fields are populated incrementally as each node completes its work.
    """

    # Input
    query: str
    session_id: str

    # Planner output
    steps: list[dict[str, Any]]  # [{"step": 1, "description": "...", "type": "code|chart|insight"}]
    expected_output: str

    # Code Interpreter output
    code: str
    exec_result: dict[str, Any]  # {"success": bool, "output": str, "data_snapshot": ...}

    # Visualization output
    chart_json: dict[str, Any] | None  # Plotly figure JSON

    # Insight output (final)
    report: str

    # Error tracking
    error: str | None
    current_step: str  # node name currently executing — used for SSE progress


# ---------------------------------------------------------------------------
# Node: Planner
# ---------------------------------------------------------------------------

async def planner_node(state: AnalysisState) -> AnalysisState:
    """Decompose user query into structured analysis steps via LLM."""
    logger.info(f"[Planner] Decomposing query: {state['query'][:80]}...")
    state["current_step"] = "planner"

    try:
        result = await plan_analysis(state["query"], state.get("session_id", ""))
        state["steps"] = result["steps"]
        state["expected_output"] = result.get("expected_output", "")
        state["error"] = None
        logger.info(f"[Planner] Generated {len(state['steps'])} steps")
    except Exception as e:
        logger.error(f"[Planner] Failed: {e}")
        state["error"] = str(e)
        state["steps"] = []
        state["expected_output"] = ""

    return state


# ---------------------------------------------------------------------------
# Node: Code Interpreter (real — Day 3)
# ---------------------------------------------------------------------------

async def code_interpreter_node(state: AnalysisState) -> AnalysisState:
    """Generate & execute Python analysis code via LLM + Self-Healing retry.

    Day 3: Real LLM code generation → sandbox execution → 3-retry self-healing.
    Executes code-type steps + automatic Data Understanding (step 0).
    Chart-type and insight-type steps pass through to their respective agents.
    """
    logger.info("[CodeInterpreter] Starting real code execution...")
    state["current_step"] = "code_interpreter"

    if state.get("error"):
        return state

    steps = state.get("steps", [])
    session_id = state.get("session_id", "")

    if not steps or not session_id:
        state["error"] = "Missing steps or session_id"
        return state

    try:
        result = await execute_analysis(steps=steps, session_id=session_id)
    except Exception as e:
        logger.error(f"[CodeInterpreter] Execution failed: {e}")
        state["exec_result"] = {"success": False, "error": str(e), "output": "", "results": []}
        state["error"] = str(e)
        return state

    state["exec_result"] = result
    state["code"] = "(generated by Code Interpreter Agent — see exec_result.results for per-step details)"

    if not result.get("success"):
        logger.warning("[CodeInterpreter] Some steps failed — continuing downstream")
        # Don't set state["error"] — let downstream agents work with partial results

    logger.info(
        f"[CodeInterpreter] Done: {len(result.get('results', []))} steps, "
        f"success={result.get('success')}"
    )
    return state


# ---------------------------------------------------------------------------
# Node: Visualization (real — Day 4)
# ---------------------------------------------------------------------------

async def visualization_node(state: AnalysisState) -> AnalysisState:
    """Auto-select chart type, generate Plotly code, execute in sandbox.

    Day 4: Real LLM chart generation with auto type selection + retry self-healing.
    """
    logger.info("[Visualization] Generating chart via LLM...")
    state["current_step"] = "visualization"

    if state.get("error"):
        return state

    exec_result = state.get("exec_result", {})
    query = state.get("query", "")
    steps = state.get("steps", [])
    session_id = state.get("session_id", "")

    # Extract chart-type steps from planner
    chart_steps = [s for s in steps if s.get("type") == "chart"]

    # If no chart steps, check if query implies visualization
    if not chart_steps:
        chart_keywords = ["趋势", "图", "chart", "对比", "分布", "占比", "变化", "增长"]
        if any(kw in query for kw in chart_keywords):
            chart_steps = [{"description": query, "type": "chart"}]

    if not chart_steps or not session_id:
        logger.info("[Visualization] No chart steps — skipping")
        state["chart_json"] = None
        return state

    try:
        chart_json = await generate_chart(
            exec_result=exec_result,
            query=query,
            chart_steps=chart_steps,
            session_id=session_id,
        )
        state["chart_json"] = chart_json
        state["error"] = None if chart_json else "图表生成失败：LLM 未能产出有效 JSON"
        logger.info(
            "[Visualization] Chart generated: %s",
            "OK" if chart_json else "FAILED",
        )
    except Exception as e:
        logger.error(f"[Visualization] Failed: {e}")
        state["chart_json"] = None
        state["error"] = str(e)

    return state


# ---------------------------------------------------------------------------
# Node: Insight (real — Day 5)
# ---------------------------------------------------------------------------

async def insight_node(state: AnalysisState) -> AnalysisState:
    """Synthesize analysis results + chart + knowledge into a 4-section report.

    Day 5: Real LLM report generation with MCP knowledge injection.
    Report sections: 数据事实 / 图表说明 / 业务解读 / 数据来源
    """
    logger.info("[Insight] Generating report with LLM + MCP knowledge...")
    state["current_step"] = "insight"

    if state.get("error"):
        return state

    exec_result = state.get("exec_result", {})
    chart_json = state.get("chart_json")
    query = state.get("query", "")
    steps = state.get("steps", [])
    session_id = state.get("session_id", "")

    if not query:
        state["error"] = "Missing query for insight generation"
        state["report"] = ""
        return state

    try:
        report = await generate_insight_report(
            exec_result=exec_result,
            chart_json=chart_json,
            query=query,
            steps=steps,
            session_id=session_id,
        )
        state["report"] = report
        state["error"] = None
        logger.info(f"[Insight] Report generated ({len(report)} chars)")
    except Exception as e:
        logger.error(f"[Insight] Failed: {e}")
        state["report"] = f"## 报告生成失败\n\n分析流程已完成，但报告生成时出错：{str(e)}\n\n请重试或联系管理员。"
        state["error"] = str(e)

    return state


# ---------------------------------------------------------------------------
# Build & Compile Graph
# ---------------------------------------------------------------------------

def build_graph() -> StateGraph:
    """Construct the 4-node serial DAG and compile it.

    Topology:
        planner → code_interpreter → visualization → insight → END

    Each node reads/writes AnalysisState fields. If any node sets `error`,
    downstream nodes skip heavy work and pass through.
    """
    workflow = StateGraph(AnalysisState)

    # Register nodes
    workflow.add_node("planner", planner_node)
    workflow.add_node("code_interpreter", code_interpreter_node)
    workflow.add_node("visualization", visualization_node)
    workflow.add_node("insight", insight_node)

    # Serial edges
    workflow.set_entry_point("planner")
    workflow.add_edge("planner", "code_interpreter")
    workflow.add_edge("code_interpreter", "visualization")
    workflow.add_edge("visualization", "insight")
    workflow.add_edge("insight", END)

    return workflow.compile()


# Module-level compiled graph instance
analysis_graph = build_graph()
